name: "Flutter Analyze Action"
description: "Analyzes a Flutter project and posts comments on the PR for detected issues"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v2

    - name: "Set up Flutter"
      uses: subosito/flutter-action@v2

    - name: "Run Flutter Analyze Script"
      run: $GITHUB_ACTION_PATH/run_action.sh
      shell: bash
      env:
        GITHUB_TOKEN_INPUT: ${{ inputs.token }}
        GITHUB_REPOSITORY_ENV: ${{ github.repository }}
        GITHUB_SHA_ENV: ${{ github.event.pull_request.head.sha }}
        GITHUB_PULL_REQUEST_NUMBER_ENV: ${{ github.event.pull_request.number }}
